// Generated by docs/nextjs-seo-kit/build.py
"use client";

import { useState, type FormEvent } from "react";

export function UsernameSearchInput() {
  const [username, setUsername] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const value = username.trim().replace(/^@+/, "");
    if (!value) return;
    const params = new URLSearchParams({ tool: "username", q: value });
    window.location.assign(`https://www.myrecon.xyz/#${params.toString()}`);
  }
  return (
    <form onSubmit={submit} aria-label="Search a public username">
      <label htmlFor="seo-username">Username</label>
      <div>
        <input id="seo-username" name="username" type="text" value={username}
          onChange={(event) => setUsername(event.target.value)} autoComplete="off"
          autoCapitalize="none" spellCheck={false} maxLength={100}
          placeholder="Enter a username" required />
        <button type="submit">Search public platforms</button>
      </div>
      <p>Use usernames you own or are authorized to review. Results require manual confirmation.</p>
    </form>
  );
}
