/* Vercel build step: inject the backend API base URL from an environment
 * variable into a static JS file, so no backend URL is ever hardcoded.
 *
 *   Vercel → Project → Settings → Environment Variables → API_BASE_URL
 *   e.g. https://myrecon-api.onrender.com
 *
 * If API_BASE_URL is unset, the app falls back to same-origin requests (use
 * this together with a rewrite proxy in vercel.json).
 *
 * IMPORTANT: the value set here must also appear in the `connect-src`
 * directive of the Content-Security-Policy in vercel.json. The browser
 * enforces that list, so pointing this at a new API host without adding it
 * there means every lookup is blocked before it leaves the page, and the
 * only sign is a CSP error in the console.
 */
const fs = require("fs");
const path = require("path");

const apiBase = (process.env.API_BASE_URL || "").trim().replace(/\/$/, "");
const out = path.join(__dirname, "..", "assets", "js", "env.js");

// Firebase web config for Google sign-in (assets/js/account.js). Every value
// here is public by design: a Firebase web API key identifies the project, it
// does not authorise anything; the database rules and the server's token check
// do that. Leave FIREBASE_WEB_API_KEY unset and accounts simply stay off.
//
// The key comes from Vercel's environment, never a literal here, even though
// it is public: the Security workflow fails on any AIza-shaped string, and
// that guard exists because a real Google key once sat in this tree.
// The app id default is the "MyRecon web" app in myrecon-bugsnaps (25 Sep
// 2026). Deliberately no measurementId / Analytics: it would add collection
// the privacy policy does not declare, the same reason the app has none.
const fbKey = (process.env.FIREBASE_WEB_API_KEY || "").trim();
const fbAppId = (process.env.FIREBASE_WEB_APP_ID || "1:549280929178:web:cadd9e52ec56f410945623").trim();
const fbProject = (process.env.FIREBASE_PROJECT_ID || "myrecon-bugsnaps").trim();
const firebase = fbKey && fbAppId
  ? {
      apiKey: fbKey,
      appId: fbAppId,
      projectId: fbProject,
      authDomain: (process.env.FIREBASE_AUTH_DOMAIN || `${fbProject}.firebaseapp.com`).trim(),
    }
  : null;

const contents =
  "/* Generated by scripts/gen-env.js, do not edit. */\n" +
  `window.MYRECON_API_BASE = ${JSON.stringify(apiBase)};\n` +
  `window.MYRECON_FIREBASE = ${JSON.stringify(firebase)};\n`;

fs.writeFileSync(out, contents);
console.log(`[gen-env] API base set to: ${apiBase || "(same-origin)"}`);
console.log(`[gen-env] Accounts: ${firebase ? "on (" + fbProject + ")" : "off (FIREBASE_WEB_API_KEY unset)"}`);
