/* Vercel build step: inject the backend API base URL from an environment
 * variable into a static JS file, so no backend URL is ever hardcoded.
 *
 *   Vercel → Project → Settings → Environment Variables → API_BASE_URL
 *   e.g. https://myrecon-api.onrender.com
 *
 * If API_BASE_URL is unset, the app falls back to same-origin requests (use
 * this together with a rewrite proxy in vercel.json).
 *
 * IMPORTANT: the value set here must also appear in the `connect-src`
 * directive of the Content-Security-Policy in vercel.json. The browser
 * enforces that list, so pointing this at a new API host without adding it
 * there means every lookup is blocked before it leaves the page, and the
 * only sign is a CSP error in the console.
 */
const fs = require("fs");
const path = require("path");

const apiBase = (process.env.API_BASE_URL || "").trim().replace(/\/$/, "");
const out = path.join(__dirname, "..", "assets", "js", "env.js");

const contents =
  "/* Generated by scripts/gen-env.js, do not edit. */\n" +
  `window.MYRECON_API_BASE = ${JSON.stringify(apiBase)};\n`;

fs.writeFileSync(out, contents);
console.log(`[gen-env] API base set to: ${apiBase || "(same-origin)"}`);
