#!/usr/bin/env python3
"""Build reviewed Next.js App Router pages and a canonical XML sitemap.

Usage: python build.py [--data data/content] [--output /path/to/next-project]
Requires: pip install -r requirements.txt
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import date, timedelta
from pathlib import Path
from urllib.parse import urlparse
from xml.etree import ElementTree as ET

from jsonschema import Draft202012Validator, FormatChecker

HERE = Path(__file__).resolve().parent
SCHEMAS = {name: json.loads((HERE / "schemas" / f"{name}.schema.json").read_text(encoding="utf-8"))
           for name in ("comparison", "target", "deletion", "guide", "core")}
SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
CLUSTERS = {"comparison": "vs", "target": "find", "deletion": "privacy", "guide": "guides"}
SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"
MARKER = "Generated by docs/nextjs-seo-kit/build.py"
ET.register_namespace("", SITEMAP_NS)


def fail(message: str) -> None:
    raise ValueError(message)


def validate_record(record: dict, seen_paths: set[str], seen_titles: set[str]) -> str:
    kind = record.get("kind")
    if kind not in SCHEMAS:
        fail(f"Unknown kind: {kind!r}")
    errors = sorted(Draft202012Validator(SCHEMAS[kind], format_checker=FormatChecker()).iter_errors(record),
                    key=lambda error: str(error.path))
    if errors:
        fail(f"{kind}/{record.get('slug')}: " + "; ".join(error.message for error in errors))
    slug = record["slug"]
    if not SLUG.fullmatch(slug):
        fail(f"Invalid slug: {slug}")
    path = "/" if kind == "core" and slug == "home" else (
        f"/{slug}" if kind == "core" else f"/{CLUSTERS[kind]}/{slug}")
    if path in seen_paths:
        fail(f"Duplicate route: {path}")
    if record["title"].casefold() in seen_titles:
        fail(f"Duplicate title: {record['title']}")
    seen_paths.add(path)
    seen_titles.add(record["title"].casefold())
    reviewed = date.fromisoformat(record["reviewed_at"])
    if reviewed > date.today():
        fail(f"Future review date: {path}")
    if date.fromisoformat(record["modified_at"]) > date.today():
        fail(f"Future modification date: {path}")
    for source in record["sources"]:
        parsed = urlparse(source)
        if parsed.scheme != "https" or not parsed.netloc:
            fail(f"Source must be HTTPS: {source}")
    if record["status"] == "published":
        if "sample" in record["reviewer"].casefold() or "placeholder" in record["reviewer"].casefold():
            fail(f"Editorial sample cannot be published: {path}")
        if reviewed < date.today() - timedelta(days=180):
            fail(f"Review older than 180 days: {path}")
    if kind == "comparison" and record["benchmark"] is not None:
        bench = record["benchmark"]
        if not bench["methodology"] or not bench["sample_size"]:
            fail(f"Benchmark needs method and sample size: {path}")
    return path


def js_string(value: object) -> str:
    return json.dumps(value, ensure_ascii=False).replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")


def page_source(record: dict, path: str, site: str) -> str:
    data = js_string(record)
    url = site + path
    depth = len([part for part in path.strip("/").split("/") if part])
    component_import = ("../" * (depth + 1)) + "components/UsernameSearchInput"
    # JSON is inlined as a TS const so build output has no runtime data fetch.
    return f'''// {MARKER}
import type {{ Metadata }} from "next";
import {{ UsernameSearchInput }} from {js_string(component_import)};

// Input is validated against a strict kind-specific JSON Schema before emission.
const page: any = {data};
const canonical = {js_string(url)};

export const metadata: Metadata = {{
  title: page.title,
  description: page.description,
  alternates: {{ canonical }},
  robots: {{ index: true, follow: true }},
  openGraph: {{ title: page.title, description: page.description, url: canonical, type: "article" }},
}};

export default function Page() {{
  const ld = {{
    "@type": page.kind === "target" || page.kind === "core" ? "WebPage" : "Article",
    headline: page.h1,
    description: page.description,
    dateModified: page.modified_at,
    mainEntityOfPage: canonical,
  }};
  const faqLd = page.faq?.length ? {{
    "@type": "FAQPage",
    mainEntity: page.faq.map((item: {{ question: string; answer: string }}) => ({{
      "@type": "Question", name: item.question,
      acceptedAnswer: {{ "@type": "Answer", text: item.answer }},
    }})),
  }} : null;
  const graph = {{ "@context": "https://schema.org", "@graph": [ld, ...(faqLd ? [faqLd] : [])] }};
  return (
    <main id="main" className="seo-page">
      <article>
        <nav aria-label="Breadcrumb"><a href="/">Home</a> / <span>{{page.h1}}</span></nav>
        <h1>{{page.h1}}</h1>
        <p className="lead">{{page.intro}}</p>
        {{page.sections.map((section: {{ heading: string; body: string }}, i: number) => (
          <section key={{i}}><h2>{{section.heading}}</h2><p>{{section.body}}</p></section>
        ))}}
        {{page.kind === "comparison" && (
          <><section><h2>Capability comparison</h2><table><thead><tr><th>Capability</th><th>MyRecon</th><th>{{page.competitor.name}}</th><th>Evidence</th></tr></thead><tbody>
            {{page.capabilities.map((row: {{ name: string; myrecon: string; competitor: string; evidence_url: string }}, i: number) => <tr key={{i}}><th>{{row.name}}</th><td>{{row.myrecon}}</td><td>{{row.competitor}}</td><td><a href={{row.evidence_url}}>Source</a></td></tr>)}}
          </tbody></table></section>
          {{page.benchmark ? <section><h2>Measured speed</h2><p>{{page.benchmark.methodology}}</p><p>Sample: {{page.benchmark.sample_size}} checks; measured {{page.benchmark.measured_at}}. MyRecon: {{page.benchmark.myrecon_seconds}} seconds; {{page.competitor.name}}: {{page.benchmark.competitor_seconds}} seconds.</p></section> : <p>No comparable speed benchmark has been published.</p>}}
          <section><h2>Strengths and limits</h2><h3>Advantages</h3><ul>{{page.pros.map((x: string, i: number) => <li key={{i}}>{{x}}</li>)}}</ul><h3>Limitations</h3><ul>{{page.cons.map((x: string, i: number) => <li key={{i}}>{{x}}</li>)}}</ul></section>
          <section><h2>Moving from a CLI workflow</h2><p>{{page.migration_note}}</p></section>
          </>
        )}}
        {{page.kind === "target" && (
          <><section><h2>Check a public username</h2><UsernameSearchInput /><p>{{page.platform.limitations}}</p></section>
          <section><h2>Manual search steps</h2><ol>{{page.manual_steps.map((step: string, i: number) => <li key={{i}}>{{step}}</li>)}}</ol></section>
          <section><h2>Privacy and false positives</h2><p>{{page.platform.privacy_overview}}</p><p>{{page.platform.false_positive_note}}</p></section></>
        )}}
        {{page.kind === "deletion" && (
          <><section><h2>Deletion steps</h2><ol>{{page.steps.map((step: string, i: number) => <li key={{i}}>{{step}}</li>)}}</ol><p>{{page.caveat}}</p><p><a href={{page.official_help_url}}>Current official instructions</a></p>{{page.optout_link && <p><a href={{page.optout_link}}>Official opt-out page</a></p>}}</section>
          <section><h2>Find what remains</h2><p>{{page.audit_pitch}}</p></section></>
        )}}
        {{page.kind === "guide" && <section><h2>Key takeaways</h2><ul>{{page.takeaways.map((x: string, i: number) => <li key={{i}}>{{x}}</li>)}}</ul><p>{{page.method}}</p></section>}}
        {{page.kind === "core" && <section><h2>What the product does</h2><ul>{{page.product_claims.map((x: string, i: number) => <li key={{i}}>{{x}}</li>)}}</ul></section>}}
        <section><h2>Frequently asked questions</h2>{{page.faq.map((item: {{ question: string; answer: string }}, i: number) => <div key={{i}}><h3>{{item.question}}</h3><p>{{item.answer}}</p></div>)}}</section>
        {{page.kind !== "target" && <section className="seo-cta"><h2>Check a username on public platforms</h2><UsernameSearchInput /></section>}}
        <p><a href={{page.cta.href}}>{{page.cta.label}}</a></p>
        <p><small>Reviewed {{page.reviewed_at}} · <a href={{page.sources[0]}}>Primary source</a></small></p>
      </article>
      <script type="application/ld+json" dangerouslySetInnerHTML={{{{ __html: JSON.stringify(graph).replace(/</g, "\\\\u003c") }}}} />
    </main>
  );
}}
'''


def build(data_path: Path, output: Path, site: str, minimum: int) -> int:
    output = output.resolve()
    parsed = urlparse(site)
    if parsed.scheme != "https" or not parsed.netloc or parsed.path not in ("", "/"):
        fail("--site must be an HTTPS origin without a path")
    if data_path.is_dir():
        payload = []
        content_files = sorted(data_path.rglob("*.json"))
        if not content_files:
            fail(f"No content JSON files found in {data_path}")
        for content_file in content_files:
            record = json.loads(content_file.read_text(encoding="utf-8"))
            if not isinstance(record, dict):
                fail(f"Each content file must contain one JSON object: {content_file}")
            payload.append(record)
    else:
        payload = json.loads(data_path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        fail("Dataset root must be an array")
    seen_paths: set[str] = set()
    seen_titles: set[str] = set()
    entries = []
    for record in payload:
        path = validate_record(record, seen_paths, seen_titles)
        if record["status"] != "published":
            continue
        entries.append((path, record))
    if len(entries) < minimum:
        fail(f"Only {len(entries)} published pages; --minimum requires {minimum}")
    if len(entries) > 50_000:
        fail("Split the sitemap at 50,000 URLs")

    # Validate the entire dataset and all output collisions before writing.
    manifest = output / ".seo-nextjs-manifest.json"
    previous = json.loads(manifest.read_text(encoding="utf-8")) if manifest.exists() else []
    if not isinstance(previous, list):
        fail("Invalid generated-file manifest")
    current = {str(Path("app") / path.lstrip("/") / "page.tsx") for path, _ in entries}
    stale = []
    for relative in previous:
        if not isinstance(relative, str):
            fail("Invalid generated-file manifest path")
        target = (output / relative).resolve()
        if not target.is_relative_to(output / "app") or target.name != "page.tsx":
            fail(f"Manifest path escapes app directory: {relative}")
        if relative not in current and target.exists():
            if MARKER not in target.read_text(encoding="utf-8"):
                fail(f"Refusing to remove edited page: {target}")
            stale.append(target)
    for path, _ in entries:
        target = output / "app" / path.lstrip("/") / "page.tsx"
        if target.exists() and MARKER not in target.read_text(encoding="utf-8"):
            fail(f"Refusing to overwrite authored page: {target}")
    sitemap = output / "public" / "sitemap.xml"
    if sitemap.exists() and MARKER not in sitemap.read_text(encoding="utf-8"):
        fail(f"Refusing to overwrite authored sitemap: {sitemap}")
    component = output / "components" / "UsernameSearchInput.tsx"
    component_marker = "Generated by docs/nextjs-seo-kit/build.py"
    if component.exists() and component_marker not in component.read_text(encoding="utf-8"):
        fail(f"Refusing to overwrite authored component: {component}")

    for target in stale:
        target.unlink()
    for path, record in entries:
        directory = output / "app" / path.lstrip("/")
        directory.mkdir(parents=True, exist_ok=True)
        target = directory / "page.tsx"
        target.write_text(page_source(record, path, site.rstrip("/")), encoding="utf-8")

    component.parent.mkdir(parents=True, exist_ok=True)
    component.write_text(f'''// {component_marker}
"use client";

import {{ useState, type FormEvent }} from "react";

export function UsernameSearchInput() {{
  const [username, setUsername] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) {{
    event.preventDefault();
    const value = username.trim().replace(/^@+/, "");
    if (!value) return;
    const params = new URLSearchParams({{ tool: "username", q: value }});
    window.location.assign(`https://www.myrecon.xyz/#${{params.toString()}}`);
  }}
  return (
    <form onSubmit={{submit}} aria-label="Search a public username">
      <label htmlFor="seo-username">Username</label>
      <div>
        <input id="seo-username" name="username" type="text" value={{username}}
          onChange={{(event) => setUsername(event.target.value)}} autoComplete="off"
          autoCapitalize="none" spellCheck={{false}} maxLength={{100}}
          placeholder="Enter a username" required />
        <button type="submit">Search public platforms</button>
      </div>
      <p>Use usernames you own or are authorized to review. Results require manual confirmation.</p>
    </form>
  );
}}
''', encoding="utf-8")

    urlset = ET.Element(f"{{{SITEMAP_NS}}}urlset")
    for path, record in sorted(entries):
        item = ET.SubElement(urlset, f"{{{SITEMAP_NS}}}url")
        for tag, value in (
            ("loc", site.rstrip("/") + path),
            ("lastmod", record["modified_at"]),
            ("changefreq", {"comparison": "monthly", "target": "monthly", "deletion": "monthly", "guide": "yearly", "core": "weekly"}[record["kind"]]),
            ("priority", {"comparison": "0.7", "target": "0.8", "deletion": "0.6", "guide": "0.6", "core": "0.9"}[record["kind"]]),
        ):
            ET.SubElement(item, f"{{{SITEMAP_NS}}}{tag}").text = value
    tree = ET.ElementTree(urlset)
    ET.indent(tree, space="  ")
    public = output / "public"
    public.mkdir(parents=True, exist_ok=True)
    xml = ET.tostring(urlset, encoding="unicode")
    sitemap.write_text(f'<?xml version="1.0" encoding="UTF-8"?>\n<!-- {MARKER} -->\n{xml}\n', encoding="utf-8")
    manifest.write_text(json.dumps(sorted(current), indent=2) + "\n", encoding="utf-8")
    print(f"Built {len(entries)} published pages and {public / 'sitemap.xml'}")
    return len(entries)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=HERE / "data" / "content")
    parser.add_argument("--output", type=Path, default=HERE / "generated-next-app")
    parser.add_argument("--site", default="https://www.myrecon.xyz")
    parser.add_argument("--minimum", type=int, default=200, help="Minimum number of published routes")
    args = parser.parse_args()
    build(args.data, args.output, args.site, args.minimum)
